### PR TITLE
Reminder Notifications #4 

### PR DESCRIPTION
**Pull request by MonuGit9**
Updated

### CODE REVIEW

**Comment by Dev-Panwar** [comment]
After thorough testing of the changes made by you. We are Accepting your PR. Thanks for the Contribution. Happy Hacking.

**Comment by MonuGit9** [comment]
why your repo excluded from Hacktoberfest ?   what the reason can you tell
my all PRs are excluded in website

**Comment by Dev-Panwar** [comment]
This just happened after I merged your last PR, I am working on  why this happened.

**Comment by MonuGit9** [comment]
No idea, but try to solve 
I have no intention for spam

**Pull request merged**
